#include <stdlib.h>
#include <string.h>

#include "driver.h"
#include "util.h"

// These are generated by the WASI SDK during build
const char* dotnet_wasi_getentrypointassemblyname();

entry_points_err_t find_entry_points(const char* attr_name, MonoObject** attr_obj, MonoMethod** handler) {
    MonoAssembly* assembly = mono_assembly_open(dotnet_wasi_getentrypointassemblyname(), NULL);
    if (!assembly) {
        return EP_ERR_NO_ENTRY_ASSEMBLY;
    }

    return EP_ERR_OK;
}
